server:
    port: 9903
    tomcat.uri-encoding: UTF-8

spring:
  data:
    mongodb:
      host: 172.31.224.181
      port: 27017
      username: dcpay
      password: hYocUIctcEIzZ3XDAyw5
      database: dcpay
      authentication-database: dcpay
  resources:
    add-mappings: true
  jackson:
    default-property-inclusion: NON_NULL

  rabbitmq:
    username: admin
    password: LThex6d9KnFDxapueRHO
    host: 172.31.224.223
    port: 5672





web3Url: http://172.31.224.181:8545
gasPrice:
gasLimit:

transactionTimeOut: 600000 # 超时未确认的
